### ISSUE TITLE
[MIG-249] Support new rollback workflow

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-ui#1027]
Hey @vconzola, in [mig-controller#663](https://github.com/konveyor/mig-controller/issues/663) Marek is implementing the ability for a user to perform a rollback of everything that has been migrated so far for a MigPlan.

In the new system:

- Rollback only happens when the user asks for it after execution of a migration
- Auto-rollback ceases to exist
- Users are expected to evaluate the state of the world and decide if they want to roll back
- Rollback will cover everything migrated by a MigPlan, instead of just covering resources migrated by a MigMigration.

My thought is that we can implement a plan-level control in the UI for this. I think a kebab menu item could be suitable, but want your input. 

cc @aufi 

---

Changes needed:
- add a rollback button to plan kebab ([screenshot](https://github.com/konveyor/mig-ui/issues/1027#issuecomment-702178521))
  - this should trigger warning modal, see mockups from Vince
  - button should only be clickable after a migration has finished running (can be successful or failed)
- when `migmigation.spec.rollback = true`, change migration "Type" in UI to "Rollback" ([screenshot](https://github.com/konveyor/mig-ui/issues/1027#issuecomment-708401328))

**Comment by vconzola** [comment]
@djwhatle Yeah, a kebab action seems like the right place for a Rollback action. I'm not sure if it belongs on the plan or the migration though? A couple questions... 

1. Rollback only makes sense after a Migrate, not a Stage, correct?
2. Should Rollback be available for successful Migrates, or only those that Failed or PartiallyFailed?

 
We'll also want a confirmation dialog that explains exactly what a rollback does in terms a user will understand. I'll need your help with the text for this once I start working on mockups.

**Comment by djwhatle** [comment]
@vconzola

1. I think rollback of work done on the plan should be possible after any type of migration (stage or migrate). We create OpenShift resources on the destination cluster in both `stage` and `migrate`. The new implementation of rollback finds everything that has been created due to a MigPlan and rolls it back.

2. I think the user should always have the option of reverting their changes with rollback, no matter what _we_ declare as success, failure, or partial failure.

I agree on the confirmation dialog. We want to communicate that everything in the migrated so far for the entire Migration Plan will be rolled back.

**Comment by djwhatle** [comment]
Did an in-place edit of where I was proposing the rollback button would go

![image](https://user-images.githubusercontent.com/7576968/94823240-a539aa00-03d1-11eb-89ae-5ec646fa143f.png)

**Comment by vconzola** [comment]
@djwhatle Yep, that's where it belongs.

**Comment by aufi** [comment]
Adding screenshot on current Migration list, it should needed to be updated to allow identify Migration and Rollback
![image](https://user-images.githubusercontent.com/555381/95995362-ae932f80-0e31-11eb-91ed-8b5206eab339.png)

**Comment by eriknelson** [comment]
@vconzola did we owe you some UI copy for a tooltip somewhere? I have a note about this but it doesn't have the details.

**Comment by vconzola** [comment]
@eriknelson The confirmation text when selecting rollback needs to be vetted / edited / improved. https://docs.google.com/presentation/d/1H57u_fYn_qTVbVM-qXJ4do-s5HalG0LsaOO4dSGaS5M/edit?usp=sharing (Slide 3)
