### ISSUE TITLE
Migration Analytics filter: Provider > Provider name

### ISSUE THREAD

**Issue by apinnick** [konveyor/mig-ui#1032]
For filtering a workload inventory report in Migration Analytics, the filter "Provider" should be changed to "Provider name". "Provider" suggests a generic provider like VMware but the field actually refers to the **name** of the provider environment. 

![image](https://user-images.githubusercontent.com/31725355/96460746-3a3efe80-122c-11eb-8baa-1b9b29ddfae4.png)

**Comment by eriknelson** [comment]
Not sure what UI this is, but this project is the MTC repo and not the correct place for this.
