### ISSUE TITLE
Enable 'copy oc get command' for resources other than plan/migrate

### ISSUE THREAD

**Issue by ibolton336** [konveyor/mig-ui#1033]
Inside the TreeActionsDropdown, we build an oc command for getting a specific resource from the oc cli. We need to decide where the  resource lives (source or destination) & indicate to the user which cluster to run the oc command on. 

Examples of resources we will be presented with:

```
kind: "Restore"
namespace: "openshift-migration"
name: "2d664340-1483-11eb-9b20-99dbdd85b490-mltbn"
children: (6) [{…}, {…}, {…}, {…}, {…}, {…}]
objectLink: "/namespaces/openshift-migration/clusters/host/namespaces/openshift-migration/restores/2d664340-1483-11eb-9b20-99dbdd85b490-mltbn"
__proto__: Object
```

```
kind: "PodVolumeRestore"
namespace: "openshift-migration"
name: "cb626470-0367-11eb-9229-7fe8551ebd2a-xcblt-pjtgq"
objectLink: "/namespaces/openshift-migration/clusters/host/namespaces/openshift-migration/podvolumerestores/cb626470-0367-11eb-9229-7fe8551ebd2a-xcblt-pjtgq"
__proto__: Object
```
```
kind: "Plan"
namespace: "openshift-migration"
name: "fffdsfa"
children: [{…}]
objectLink: "/namespaces/openshift-migration/plans/fffdsfa"
__proto__: Object
```
```
kind: "Migration"
namespace: "openshift-migration"
name: "2d664340-1483-11eb-9b20-99dbdd85b490"
children: (2) [{…}, {…}]
objectLink: "/namespaces/openshift-migration/migrations/2d664340-1483-11eb-9b20-99dbdd85b490"
__proto__: Object
```

```
kind: "Backup"
namespace: "openshift-migration"
name: "2d664340-1483-11eb-9b20-99dbdd85b490-bkbpn"
objectLink: "/namespaces/openshift-migration/clusters/src/namespaces/openshift-migration/backups/2d664340-1483-11eb-9b20-99dbdd85b490-bkbpn"
__proto__: Object
```

It looks like we will need to manipulate the data we receive from the discovery service and derive some ui specific state to indicate which cluster it should be run on. That way we can show this to the user in an elegant way. What are your thoughts @vconzola ... add more text to the dropdown selection to indicate "run on source" etc?

**Comment by vconzola** [comment]
@ibolton336 I suggest we trigger a success inline notification that says, "Copied to clipboard. Run the oc get command on cluster_xyz to view resource details." or something like that. Text should be vetted by @erik or someone who knows better than I what the oc get command does. "Copied to clipboard should be the alert title and the rest is the supporting text below.  Let me know if you need a mockup.

**Comment by eriknelson** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1890525

**Comment by eriknelson** [comment]
PodVolumeBackups and Backups will always be run on the source cluster, PodVolumeRestores and Restores will always be on the target.
