### ISSUE TITLE
MIgration options > Persistent volumes: Direct migration text

### ISSUE THREAD

**Issue by apinnick** [konveyor/mig-ui#1067]
In the "Migration options" screen of the "Create migration plan" wizard, the text under "Persistent volumes" is "Direct image migration". Should that be "Direct PV migration"? 

![20201118_114923](https://user-images.githubusercontent.com/31725355/99520155-6ec4e800-299b-11eb-9363-a1e8cc3aa345.png)

**Comment by pranavgaikwad** [comment]
@apinnick thanks! this should read `Direct PV migration` and not `Direct image migration`
