### ISSUE TITLE
[MIG-443] Need design for improved hook UX (status & logs)

### ISSUE THREAD

**Issue by eriknelson** [konveyor/mig-ui#1084]
Placeholder for design discussion around hook logs and status in the UI (see: https://issues.redhat.com/browse/MIG-443)

**Comment by eriknelson** [comment]
We should explore hyperlinking the resources that are on the debug page into the associated pages in the main console.

**Comment by vconzola** [comment]
@eriknelson That's funny. I had the exact same thought when y'all were talking about this during 1.5 planning yesterday.

**Comment by eriknelson** [comment]
+1, I think there's probably some well-defined path structure we can take
advantage of and that's going to be a lot better than reinventing the wheel
ourselves.

**Comment by eriknelson** [comment]
Closing as obsolete. We've decided we expect to handle this in some existing ways (namely dynamic pipelines) that won't require a major design.
