### ISSUE TITLE
[MIG-443] Ensure hook related resources from disco svc response render in debug view

### ISSUE THREAD

**Issue by eriknelson** [konveyor/mig-ui#1112]
The hooks, job, and pod that are related to a particular migration as they spawn (if they exist)
to the debug resources page. This requires a discovery service update to provide this data. 
We think the debug resources page should be able to just render this addition to the payload,
but Ian Bolton will likely need to ensure this is true, or make adjustments in case anything is broken.

**Comment by djwhatle** [comment]
Resolved by #1164
