### ISSUE TITLE
Cannot start mig-ui locally

### ISSUE THREAD

**Issue by jwangyangls** [konveyor/mig-ui#1115]
I want to start this project locally, and then execute it as described in the document
yarn, yarn build, yarn start 
have been executed before cp config/config.dev.json.example config/config.dev.json, but when I open the browser, such an error will be reported：
![image](https://user-images.githubusercontent.com/29826789/106407336-c214e580-6476-11eb-9f6b-674a352647d3.png)

![image](https://user-images.githubusercontent.com/29826789/106407356-ce00a780-6476-11eb-90ed-c03b51bbbc62.png)

![image](https://user-images.githubusercontent.com/29826789/106407378-d8bb3c80-6476-11eb-94ce-3adeb72daa89.png)

I did not make any changes to the default config.dev.json

**Comment by jwangyangls** [comment]
If local start is not supported (no server); please notify me and consider whether to update the document

**Comment by ibolton336** [comment]
@jwangyangls Local is supported - you must provide a clusterApi & a discoveryApi value in the config file to a running cluster.
