### ISSUE TITLE
[Enhancement] - Integrate usePausedPollingEffect into MTC project

### ISSUE THREAD

**Issue by ibolton336** [konveyor/mig-ui#1120]
https://github.com/konveyor/mig-ui/pull/1119 Referenced here. 

This functionality captures the behavior we need for starting/stopping polling & allows us to simply call a hook in any component that requires this behavior. The hook internally contains the logic for starting/stopping polling when mounting/unmounting a component. This fits the use case for MTC nicely as we have several cases when a modal/wizard/form is mounted that needs to pause polling temporarily.

**Comment by mturley** [comment]
Equivalent code in MTV: https://github.com/konveyor/forklift-ui/blob/main/src/app/common/context/PollingContext.tsx#L68-L75

I think we'd only need that hook though and not the entire PollingContext, since that stuff is already handled in Redux.
