### ISSUE TITLE
Follow up bugs after progressive wizard PR

### ISSUE THREAD

**Issue by mturley** [konveyor/mig-ui#1362]
Opening a separate issue to follow up after merging #1361 so we can start testing it end to end, since the main use case works.

Issues observed when testing the new wizard changes and comparing them to the [mockups](https://docs.google.com/presentation/d/1eO1tPsLQst7qbj-CKD10m4dzsxG3h7bRhAulqoKy40k/edit#slide=id.p):

- [x] Crashes when trying to edit existing plan (see https://github.com/konveyor/mig-ui/pull/1361#issuecomment-988232093)

- [x] General step
  - [x] "All fields are required" text is missing
  - [x] Fields are out of order, source cluster should be before migration type
  - [x] Too much space between the fields?
  - [x] "Repository" field should be titled "Replication repository"
- [x] Namespaces step
  - [x] In storage class conversion mode, there are editable row controls but nothing to edit
  - [x] Non-PF button styles in use for editable rows
- [x] PVs step
  - [x] migration type column should be disabled until a PV is selected (when selection is a thing, state+full only?)
  - [x] Target storage class field is missing from here, should be here instead of on copy options step when in storage class conversion mode (need to check with @vconzola)
  - [x] PV migration type is still here when in storage class conversion mode, it was removed in the mockups for that mode
- [x] Copy options step
  - [x] Non-PF styles in use for editable rows

Additional implementation needed:
- [x] Plans table
  - [x] Type column (Full, state only, storage class conversion) (Fixed in #1366)
  - [x] Rearrange table to fit everything? (compact variant? expandable w/ source + target under the fold?) (Fixed in #1366)
  - [x] Remove/rename actions in the dropdown as appropriate for each migration type
  - [x] Disable the Rollback action when it is not applicable (need to discuss with @eriknelson)

**Comment by mturley** [comment]
https://github.com/konveyor/mig-ui/pull/1363 implements everything here except for:

* Plans table
  * Type column (Full, state only, storage class conversion)
  * Rearrange table to fit everything? (compact variant? expandable w/ source + target under the fold?)
  * Disable the Rollback action when it is not applicable (need to discuss with @eriknelson)

**Comment by mturley** [comment]
Per conversation with @vconzola and @pranavgaikwad, we will actually want to:
- [ ] add Stage and Cutover actions on all types of plans and not just full migrations.

**Comment by pranavgaikwad** [comment]
- [ ] For SCC/State migration plans, `indirectImageMigration` and `indirectVolumeMigration` must be set to false. 
- [ ] State migration can be performed even when one or more PVCs have `move` option selected
- [ ] For state migrations, `stage` should be set to False whenever `migrateState` is set to True.

**Comment by mturley** [comment]
Addressing stage/cutover action changes above in https://github.com/konveyor/mig-ui/pull/1368 (WIP).

**Comment by mturley** [comment]
Remaining tweaks above will be addressed in https://github.com/konveyor/mig-ui/pull/1369
