### ISSUE TITLE
Add ability to cancel a Stage/Migrate in progress

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/mig-ui#425]
Backend issue to support:  https://github.com/fusor/mig-controller/issues/237

**Comment by vconzola** [comment]
From a UI standpoint here's what's needed:

- Add a Cancel kebab action to in progress stage/migrate
- Display current migration state as Cancelling stage/migrate
- When cancel is complete show a success/failure toast notification 

Will provide mockups later.

**Comment by eriknelson** [comment]
https://issues.redhat.com/browse/MIG-118

**Comment by eriknelson** [comment]
From the controller issue, mockups: https://docs.google.com/presentation/d/1Fv8pUuAl48umIjJKEkyw1TUWR_IfMp5w8HuZXe4-l9c/edit#slide=id.p
