### ISSUE TITLE
Support ussage of HTTPS with self-hosted S3 providers by accepting CA certs

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/mig-ui#454]
Tried to use address of

https://http://minio-gpte-minio.apps.cluster-jwm.jwm.mg.example.com

Connection failed: The Backup storage cloudprovider test failed [RequestError: send request failed caused by: Put https://minio-gpte-minio.apps.cluster-jwm.jwm.mg.example.com/jwmbucket/a3965eba-bfb4-11e9-b678-0a580a830011: x509: certificate signed by unknown authority]. | TestFailed

How do we handle CA for this?
Can we also allow an insecure mode, check box perhaps from ui?

**Comment by ibolton336** [comment]
Closed via #606
