### ISSUE TITLE
Change the way mig plan states and status are displayed

### ISSUE THREAD

**Issue by vconzola** [konveyor/mig-ui#591]
To improve the UX of the migration plans list and the associated status card, we should make the following changes:

1. Add a "Closed" status to the card corresponding to a "closed" plan state.
2. To distinguish successful from failed migrations, add a "Failed" status to the card.
3. Change the heading text in the mig plan list from "Last status" to "Last state" to distinguish it from overall plan status. Multiple states can result in the same status.
4. Make the state icons consistent with the corresponding status icons.

Mockups [here](https://marvelapp.com/project/4334729/screen/61792840/comments/) and [here](https://marvelapp.com/project/4334729/screen/61795325/comments/).

This [document](https://docs.google.com/document/d/1w8nz07_ppCR5m42p5_4ricY-J6okdsjBSOqP2R_gyco/edit?usp=sharing) showing all migration plan states and their associated status and available actions might also be useful.

**Comment by eriknelson** [comment]
@vconzola these mockups are 404ing

**Comment by ibolton336** [comment]
@vconzola  Can you update the mockup links to this if this issue is still valid? Thx

**Comment by vconzola** [comment]
@ibolton336 We removed the cards from the UI when we added the the left navigation, so this issue is no longer valid. I'll close it.
