### ISSUE TITLE
Differentiate between controller error and lack of PVs

### ISSUE THREAD

**Issue by ibolton336** [konveyor/mig-ui#613]
Currently if the controller is unresponsive/ no longer updating migplan with status/conditions, the ui lets the user progress through the wizard without any warning or error message. 
Need differentiate UX for these two cases:
- pv discovery condition completed & returned no valid PVs. 
- controller unresponsive & not updating

**Comment by vconzola** [comment]
UI mockups here: [](https://docs.google.com/presentation/d/1EN7kTtOz1sv6TUESIov_X29IYVl78s11ChjvhmLyS-Q/edit?usp=sharing)

**Comment by eriknelson** [comment]
#654 and its implementation should help give us enough information to be able to tell the difference here. Right now, the UI has no idea of knowing the difference between these two conditions afaik.

**Comment by vconzola** [comment]
I think the design is done, pending review.
