### ISSUE TITLE
Need to implement the unused columns on the namespace selection screen

### ISSUE THREAD

**Issue by eriknelson** [konveyor/mig-ui#660]
![image](https://user-images.githubusercontent.com/410933/73899519-eeddef00-485a-11ea-9a1a-8ccf80231e32.png)

As seen in the image, we have 3 unpopulated columns still present that still are not hooked up to anything. The first question I'd like to answer with @vconzola and @jwmatthews is, do we still think these columns are relevant and they're desired to keep around? If that's true, we need to enhance the discovery service to provide this information as part of the nameplace discovery endpoint.

I'd also point out these have been empty for a few releases as this point and I haven't heard anything about it. Do we think this columns are really necessary, or would it be useful to do some kind of a UX redesign here built around *only* displaying namespace names.

Related controller issue: https://github.com/fusor/mig-controller/issues/414

**Comment by vconzola** [comment]
@eriknelson I can't really say how useful or necessary these columns are. Would like to hear @jwmatthews thoughts. If we don't need them I'll design using a different type of component for selection. This is related to the issue of handling large numbers of namespaces within a cluster, so I'll take that into consideration too.

**Comment by vconzola** [comment]
I also wish we hadn't combined the source/target and namespace steps of the wizard. that would allow us to show more projects per page.

**Comment by eriknelson** [comment]
This is going to depend on a breaking API change in the discovery service, [link to the design document](https://docs.google.com/document/d/1BWlSlsrV_uzjLyFVkoYmjHaNHs-F__exMAh8yTVqAeg) describing the UI schema changes required.

@jortel is there a PR link I can add here?
