### ISSUE TITLE
UX improvements to the Add/Edit Cluster and Storage forms

### ISSUE THREAD

**Issue by eriknelson** [konveyor/mig-ui#663]
After our call with @vconzola and @mansam regarding custom CA bundle support, we decided to accept those PRs as they are since they encapsulate the functionality desired for the feature, and to separately address the UX improvements that Vince raised during the call so the two PRs are not conflated with one another. I'm filing this as a placeholder issue for now because I'd like to circle back with screenshots from master so we can itemize the UX changes required and get those fixed. As of now, I'm aware of:

* We need to ensure the correct buttons are marked as primary/secondary buttons, right now they are all primary.
* The "Is azure cluster prompt" should be above the URL, but below the name field.
* The close button should be a cancel button, as seen in the following mock provided by vince:

![1](https://user-images.githubusercontent.com/410933/74277573-c71cda00-4ce5-11ea-82cc-e3a9a212b95e.png)

![1-1](https://user-images.githubusercontent.com/410933/74277580-ca17ca80-4ce5-11ea-98cf-e822e13cb00c.png)

**Comment by mturley** [comment]
Related to https://github.com/fusor/mig-ui/issues/356, discussing with @vconzola right now. I may fix this in the same PR.

**Comment by eriknelson** [comment]
@mturley be aware we intend to bring in Sam's CA bundle functional changes to master prior to making these changes. You may want to implement this on top of his PR's commits.

**Comment by mturley** [comment]
Gotcha, thanks for the heads up @eriknelson

**Comment by vconzola** [comment]
Might also want to add a popover for SSL required field as part of this.

**Comment by mturley** [comment]
Note to self: we should replace `react-select` with PatternFly's `Select` in the Storage form as part of this issue. Other occurrences of `react-select` are covered by https://github.com/konveyor/mig-ui/issues/736, https://github.com/konveyor/mig-ui/issues/585, https://github.com/konveyor/mig-ui/issues/586 and https://github.com/konveyor/mig-ui/issues/587.

**Comment by mturley** [comment]
The CA bundle file field here in the cluster form should also be converted to a PF FileUpload component as part of this issue.

@vconzola , this is lower priority, but you suggested a popover on the "Require SSL verification" field here. Do you know what text that should have?

**Comment by vconzola** [comment]
@mansam @eriknelson Can you provide some text explaining when a user would select the "Require SSL verification" checkbox?

**Comment by mturley** [comment]
When you guys get a chance to figure out the text for the "Require SSL verification" help info, I plan to get this done asap.

**Comment by eriknelson** [comment]
Hint text:

"[Cluster]
"Select 'Require SSL verification' to verify SSL connections to the cluster.
If you are using a self-signed certificate, you may either disable SSL
verification, or upload your certificate bundle."

[Replication Repository]
"Select 'Require SSL verification' to verify SSL connections to the object store.
If you are using a self-signed certificate, you may either disable SSL
verification, or upload your certificate bundle."

Spoke with @vconzola and we want this as inline hint text instead of behind a tooltip.
