### ISSUE TITLE
Pre/post ansible hooks

### ISSUE THREAD

**Issue by eriknelson** [konveyor/mig-ui#668]
https://issues.redhat.com/browse/MIG-50

~Also blocked on non-admin engineering design.~

**Comment by vconzola** [comment]
Link to mockups: https://docs.google.com/presentation/d/1WgrJ1B4J1nmgTaHW7vJq-xbgjDS8kPIQq4IBpABzvKg/edit?usp=sharing

**Comment by eriknelson** [comment]
https://issues.redhat.com/browse/MIG-50
