### ISSUE TITLE
It is confusing that you must choose AWS type to configure your own self hosted S3

### ISSUE THREAD

**Issue by eriknelson** [konveyor/mig-ui#669]
From a slack inquiry:

> Hi all, while adding replication repos to migration tool, I remember it supported any S3 storage (minio in my case). I have a build that only allows provider as aws/gcp/azure. Is that added new or am I using an older version? Thanks.

Right now, when you choose "Add Replication Repository", you are presented a dropdown with three options: "AWS", "Azure", "GCP". If you want to configure your own self hosted S3 bucket (minio or noobaa), you need to actually select AWS. The truth is, the same form is used to configure AWS *or* minio.

@vconzola What is your recommendation here? Should we just update the dropdown to read "S3" instead of AWS?

**Comment by vconzola** [comment]
@eriknelson I suggest we add a "Self-hosted S3 bucket" (if those are the correct words?) option to the dropdown whose selection loads the same form fields as AWS. Are there (or will there be) other self-hosted options other than nooba and minio? If not, we can add those two explicitly to the dropdown - five options in a dropdown is fine.

**Comment by eriknelson** [comment]
Need to follow up on this one with @jwmatthews
