### ISSUE TITLE
Add alerts with detailed message describing why a migration/stage has failed

### ISSUE THREAD

**Issue by ibolton336** [konveyor/mig-ui#674]
Via @vconzola 

![image](https://user-images.githubusercontent.com/11218376/74682542-5453a900-5194-11ea-922a-054b48af6e47.png)

When there is an _error_ condition, currently the error message is shown inline within the data list view. This issue came to light when I tried to add the same functionality for _critical_ conditions, the message was very verbose & took up too much space. We should move this information over to the existing alert system.

**Comment by eriknelson** [comment]
@vconzola Dropping needs-ux-design on this so we can talk about how we want to surface stage/failure errors long term in the UX.

**Comment by vconzola** [comment]
@eriknelson Here's the PF guidance on error handling: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/alerts-and-notifications

**Comment by ibolton336** [comment]
Closed via #733
