### ISSUE TITLE
Logo is styled to appear "clickable" but does nothing

### ISSUE THREAD

**Issue by eriknelson** [konveyor/mig-ui#676]
Hard to get a screenshot of this, but the logo in the top bar appears to be clickable, but does nothing. @vconzola I think we should decide if this should route to the main page (if, for example, you are at the logs page), or if this style should just be turned off.

**Comment by vconzola** [comment]
@eriknelson It should be turned off.

**Comment by eriknelson** [comment]
@mturley Here's a good one to pick up.
