### ISSUE TITLE
S3 clean up

### ISSUE THREAD

**Issue by rbaumgar** [konveyor/mig-ui#679]
A completed plan or an incomplete plan (stage or migrate) is using some objects on the S3 storage.

Who is doing the cleanup? How do I know which objects I can remove? You can imagine that some images and data can be huge.

who do I know what can be deleted?
how are the buckets cleaned up when a plan is completed?
currently the bucket persists but with large apps it might be a good idea to offer cleanup?"

**Comment by rbaumgar** [comment]
tested with OCP 4.2 and 4.3.

**Comment by eriknelson** [comment]
Moving discussion to controller.
