### ISSUE TITLE
Refactor any uses of redux-thunk over to redux saga

### ISSUE THREAD

**Issue by ibolton336** [konveyor/mig-ui#688]
Right now in the UI codebase, there are some areas that are particularly hard to follow. Moving to one consistent way of handling CRUD operations or "side effects" would go a long way in terms of code legibility. There are only a few areas of the app still using redux-thunk. 

While this is being done, I think it would make sense to rethink how we have our saga files structured.

**Comment by eriknelson** [comment]
@ibolton336 How much thunk is left? Wondering if this could be easily knocked out with your recent changes.

**Comment by ibolton336** [comment]
Not much, but there are some pretty significant pieces of the infrastructure tied up with thunk that I was having trouble moving over. E.g. the mig meta info is pulled in with thunk. Want to make sure we get that part right & not entirely sure how to do it right now.
