### ISSUE TITLE
Integration tests are broken and unit tests are missing

### ISSUE THREAD

**Issue by mturley** [konveyor/mig-ui#693]
Running `yarn test` fails with errors in both the cluster form spec and the storage form spec.

Jest is installed and configured, but no Jest tests exist. I think things like "has buttons disabled when input data is missing" are more easily implemented as Jest unit tests of the individual component, and integration tests should only test the interactions between different components.

Related to https://github.com/fusor/mig-ui/issues/310, but in addition to snapshot tests we should have smaller tests asserting specific things without a snapshot, e.g. we could shallow-render the form with input data missing and assert that the buttons have the `isDisabled` props set correctly. I'm open to debate how useful snapshot tests really are, anyway :)

**Comment by eriknelson** [comment]
This should absolutely be failing travis, we need to look into the travis builds and fail them if `yarn test` is not working. This is a regression.

**Comment by gildub** [comment]
@mturley, as @eriknelson commented this are 2 separate issues.
Would it be okay to split it. Maybe keep this one for the broken integration tests issue and create another one for sub-snapshot tests?

**Comment by eriknelson** [comment]
I'd like to close this issue so we can open two new issues that accurately reflect where we are currently. The "integration tests" we a long time ago were really not accomplishing anything and so they sat and rotted. I pulled them and archived them.

We need two issues, one that documents our desired strategy for integration testing, and I have a pretty good idea what this needs to look like in the long run. Separately, as @mturley pointed out, it's time to get some snapshot testing in place where feasible. I'd like to schedule a meeting with the UI team to discuss these, and out of that meeting produce these issues with our documented conclusions. I will schedule something this week, it's going to be a longer discussion than we can handle on a scrum call.

**Comment by mturley** [comment]
Sounds good, thanks guys
