### ISSUE TITLE
When adding a new Plan, 'press enter' after giving a plan name and page reloads

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/mig-ui#695]
Using CAM 1.1.1 with chrome on Linux.

I created a new plan
When asked for the name of plan, I entered 'test03' and pressed enter
Page reloads, no errors seen in JS console.

I assumed pressing 'enter' would advance to next step in wizard.

**Comment by eriknelson** [comment]
I wonder if this is something that should be inherited from patternfly?
