### ISSUE TITLE
Inconsistent code spacing/formatting

### ISSUE THREAD

**Issue by mturley** [konveyor/mig-ui#697]
This is definitely low priority, and something of a nitpick. I noticed that most files are indented with 2 spaces, but some with 4, and some of the code formatting is a little messed up (e.g. https://github.com/konveyor/mig-ui/blob/324a8fc/src/app/storage/components/AddEditStorageModal/ProviderForms/AWSForm.tsx#L284-L297). [edit: replaced this link with a specific commit because the lines had moved on master].

I noticed that Prettier is a devDependency and most of the 2-space files are formatted with it. It might be nice to run `prettier --write` on the whole repo and then maybe install `eslint-config-prettier` (to disable eslint rules that may conflict with Prettier's opinions) and `eslint-plugin-prettier` (to enforce Prettier's opinions as eslint rules).

**Comment by eriknelson** [comment]
We have a linter that should be running with CI and failing something like this. We should also have a `yarn lint:fix` target. We recently abandoned a deprecated formatter, I'm forgetting what it was, but obviously we need to update our rules and make sure that the example your giving fails the `yarn lint` target. CC @ibolton336
