### ISSUE TITLE
A Closed migplan should not allow stage, or migrate.

### ISSUE THREAD

**Issue by eriknelson** [konveyor/mig-ui#730]
![image](https://user-images.githubusercontent.com/410933/76258289-a8006200-6229-11ea-9524-02997f44bd25.png)

**Comment by sseago** [comment]
Hmm. I'm not sure about the "edit" part of this. Imagine the following:
1) Plan1 is created. It's ready to run
2) Plan2 is created, but it conflicts with plan1), so now both plans are in a non-ready state.
3) I realize I must have made an error with plan2, so I close it. Now Plan1 is ready again.
4) I look back at plan2, realize that I chose the wrong namespace (and/or wrong dest cluster), so I go to edit it and then re-open it, expecting both plans to now be ready.

**Comment by eriknelson** [comment]
![image](https://user-images.githubusercontent.com/410933/76350840-da21ca80-62e2-11ea-883c-a5d97a259ab0.png)

Current master has fixed this, so at least the big part of this issue I think has been adressed. Scott's points are valid, let's move this to a priority icebox enhancement

**Comment by gildub** [comment]
@eriknelson, so shall we allow edit even when the Plan is closed ?

**Comment by gildub** [comment]
@sseago, @eriknelson, if we can't close (close: true) or re-open (close: false) a migplan through the UI then be able to edit a migplan is not necessary. In which case we can close this issue as current master takes care of it.

**Comment by sseago** [comment]
This is probably a question for @eriknelson -- the concept of editing the plan still makes sense, but if we're forcing manual closing via the API anyway, we can just as easily tell users they must use the UI for editing closed plans too, so either way it works for me.

**Comment by eriknelson** [comment]
Going to close this since this isn't a priority issue currently.
