### ISSUE TITLE
Strange behavior around PV creation and discovery

### ISSUE THREAD

**Issue by eriknelson** [konveyor/mig-ui#731]
> I created a PV inside OCP3 source cluster after having created a Migration Plan
in the CAM tool, I wanted to migrate it from glusterfs to CephFS.
Editing the Plan was not able to discover it. I deleted the plan and created a
new one, this was able to discover it, but then the PV was not visible anymore
surfing UI for migration plan creation. Did the same thing again deleting and
recreating it, but cannot discover this PV anymore from Plan creation UI, thus
my Jenkins Pipeline migration was lacking one PV needed by the pipeline (maven).

Worth trying to reproduce this and see what is going on with this between the controller and the UI. Filing here, but this may be a collaborative effort.

**Comment by ibolton336** [comment]
@eriknelson I have a hunch that this may be resolved with the latest pv discovery updates.

**Comment by eriknelson** [comment]
I agree, closing. We can reopen if this continues to be a problem.
