### ISSUE TITLE
Misleading serviceAccountSecretRef NotFound message

### ISSUE THREAD

**Issue by spankes** [konveyor/mig-ui#752]
When adding a new cluster source:  Connection failed. Message: "The `serviceAccountSecretRef` must reference a `secret`.", Reason: "NotFound" shown in addcluster popup; however, the cluster is added successfully (OCP 4.4).

**Comment by pranavgaikwad** [comment]
This should be fixed with https://github.com/konveyor/mig-ui/pull/759
