### ISSUE TITLE
(bug): unable to deselect src/target cluster selection

### ISSUE THREAD

**Issue by ibolton336** [konveyor/mig-ui#765]
If a user accidentally selects a cluster within the src/target dropdowns inside the select resources step, the app will not allow a change to be made. 

![dropdown_bug](https://user-images.githubusercontent.com/11218376/77196785-6b025e00-6aba-11ea-8d0e-16b035b15a2c.gif)

**Comment by ibolton336** [comment]
@gildub This would be a good one to pick up.

**Comment by gildub** [comment]
This will be addressed when the Plan Wizard will be revisited.
