### ISSUE TITLE
Add table sorting and filtering to the namespaces table

### ISSUE THREAD

**Issue by vconzola** [konveyor/mig-ui#772]
In step 2 of the mig plan wizard we display a table of namespaces (projects) discovered on the source cluster. This table can be huge (100s or 1000s of rows), so the ability to sort/filter the content is needed.

**Comment by vconzola** [comment]
Related to issue: https://github.com/fusor/mig-ui/issues/426

**Comment by eriknelson** [comment]
This came up during today's labs and I'm sure will come out of summit demos. We really need to add this support sooner rather than later.

**Comment by mturley** [comment]
Duplicate of https://github.com/konveyor/mig-ui/issues/794
Was resolved by https://github.com/konveyor/mig-ui/pull/803
