### ISSUE TITLE
Add "Claims" column to PVs table in storage class step in the mig plan wizard

### ISSUE THREAD

**Issue by vconzola** [konveyor/mig-ui#773]
@dymurray got feedback from a customer that PVC info would be useful at this step. We have room to add the column to the table.

**Comment by eriknelson** [comment]
+1, would be good to get this into the next release. The hard part is getting that data if it's not already available to us, but I think we have it so I believe it should be considered "low-hanging-fruit".

**Comment by vconzola** [comment]
@eriknelson I think @mturley is going to include this as part of the UXD changes he's making to that step of the wizard. @ibolton336 told me yesterday that the claims data should be easy to pull off of the discovery service object.

**Comment by mturley** [comment]
There is already a "Claim" column, is this what this issue calls for?
![Screenshot 2020-03-26 15 55 35](https://user-images.githubusercontent.com/811963/77696007-11e76e00-6f83-11ea-8d3b-9691ec410f3f.png)

**Comment by ibolton336** [comment]
@mturley the request is for the claim to show up on the storage class table on the next screen

**Comment by mturley** [comment]
Ah, sorry, got mixed up. Thanks.

**Comment by eriknelson** [comment]
Oh, we actually needed it on the next screen with storage class assignment. Apologies that wasn't expressed. 

⁣Get BlueMail for Android ​

**Comment by mturley** [comment]
It's in the title here, I just missed it because I saw PVs table. No worries

**Comment by vconzola** [comment]
Mockup is here: https://docs.google.com/presentation/d/1hlP8wjzsO_9c9ri2rIz7o2kuIQvmKCNUhoQxTnUkHr0/edit?usp=sharing
