### ISSUE TITLE
Semicolons should be required, enforced by eslint

### ISSUE THREAD

**Issue by mturley** [konveyor/mig-ui#775]
Per @eriknelson, based on a discussion from Slack. We should add the https://eslint.org/docs/rules/semi rule at level `"error"` to our `.eslintrc.js`, ensure it causes CI to fail when semicolons are not included, and open a PR to greenlight it and add any missing semicolons.

**Comment by gildub** [comment]
@mturley, @Erik Nelson, after learning a bit more about ASI, using semicolons seems to be the right choice to be safer. Although if we want to be rock solid then we should also use TSLint to catch unused expressions: https://palantir.github.io/tslint/rules/no-unused-expression/

**Comment by mturley** [comment]
@gildub [TSLint is being deprecated](https://medium.com/palantir/tslint-in-2019-1a144c2317a9) in favor of ESLint's new TypeScript support, which we're using: https://github.com/konveyor/mig-ui/blob/master/.eslintrc.js#L9-L10

`typescript-eslint` does have an equivalent rule though, I agree we should add it: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-expressions.md

**Comment by eriknelson** [comment]
@gildub TSLint is deprecated, we used to use this and had an issue to update to use ESLint, which we've moved to.

Re: no-unused-expressions, that sounds like it's probably a healthy practice to enforce.
