### ISSUE TITLE
Need to help users understand when they should provide S3 endpoint and when to ignore

### ISSUE THREAD

**Issue by eriknelson** [konveyor/mig-ui#779]
Trying to be careful to avoid jumping to an implementation, I've seen a lot of users guess at an AWS base endpoint to hit. If they are using AWS, they should *not* input anything for an S3 root endpoint, because this is the default.

The obvious, immediate way to convey that is a tooltip or better: a note visible by default that says the above. I think that's temporary duct tape, so I wanted to file this to take a step back and think about that UX.

**Comment by dymurray** [comment]
Let's ensure we also create a documentation bugzilla that helps explain when to fill this field out and when not to.

**Comment by eriknelson** [comment]
Additionally, if a user provides an AWS root s3 endpoint, how can we make that acceptable?

**Comment by vconzola** [comment]
@dymurray @eriknelson Would one of you add a screenshot showing what the Add repository modal looks like today. Thanks.

**Comment by eriknelson** [comment]
To address this confusion, spoke with @vconzola and we'd like to split S3 configuration into two separate forms that are selectable from the initial "Add Replication Repo" dropdown: "AWS S3", and "S3".

* AWS S3 should remove the endpoint field as well as the SSL verify checkbox and upload. It should default to verify, since this should be a well-known CA.
* S3 should remain the way that it is today.

https://github.com/konveyor/mig-ui/issues/663#issuecomment-619101758 Has the SSL hint text that should be displayed on the forms:

> "[Cluster]
"Select 'Require SSL verification' to verify SSL connections to the cluster.
If you are using a self-signed certificate, you may either disable SSL
verification, or upload your certificate bundle."

> [Replication Repository]
"Select 'Require SSL verification' to verify SSL connections to the object store.
If you are using a self-signed certificate, you may either disable SSL
verification, or upload your certificate bundle."

> Spoke with @vconzola and we want this as inline hint text instead of behind a tooltip.

#829 Has the default SSL verify checkbox states:

> Cluster should default to unchecked, AWS S3 should simply default to SSL verify, and the custom CA upload can be removed. We suspect the same for GCP and Azure, but let's leave the SSL options on those forms, but default to checked. For "S3", we should leave the checkbox unchecked, but the hint text will provide guidance for when it must be uploaded.
