### ISSUE TITLE
Re-running PV discovery shows wrong info when navigating back & changing namespaces

### ISSUE THREAD

**Issue by ibolton336** [konveyor/mig-ui#781]
This issue stems from comparing the generation fields on the currentPlan & the response from a getPlan request when polling. There are cases when the generation is stale or not behaving as we expected making it impossible to determine when to rerun pv discovery/when to timeout pv discovery/etc

Related #777

**Comment by eriknelson** [comment]
I'll be picking this up when we move to using the new digest of the spec from the controller.

**Comment by ibolton336** [comment]
![pv_disc](https://user-images.githubusercontent.com/11218376/77785614-d1472d80-7032-11ea-8165-73608937271c.gif)
