### ISSUE TITLE
Provide an optional means of enabling validation of data integrity during Restores (i.e. enable Restic to use checksums)

### ISSUE THREAD

**Issue by eriknelson** [konveyor/mig-ui#788]
https://issues.redhat.com/browse/MIG-20

**Comment by mturley** [comment]
Note to self from Vince's mockups (https://docs.google.com/presentation/d/1hlP8wjzsO_9c9ri2rIz7o2kuIQvmKCNUhoQxTnUkHr0/edit#slide=id.g7f12813776_1_8):

> Checkboxes [in the "Verify copy" column] are disabled unless Filesystem copy is selected for the Copy method.
