### ISSUE TITLE
[non-admin] Break out identity creation in UI

### ISSUE THREAD

**Issue by dymurray** [konveyor/mig-ui#789]
Here are our initial thoughts on how non-admin will affect the UI workflow. We believe the primary change that needs to occur is the service account token which is added as part of the migcluster creation needs to be broken out to a separate identity creation page. If you look at https://github.com/konveyor/mig-controller/issues/389 you'll notice that we are adding a new field to the `migplan` spec which will require a secret to be consumed to communicate with the source and destination clusters as a specific identity. From an API perspective, these changes make a lot of sense but I want to get more input on whether the UI workflow would benefit from putting these API changes elsewhere.

We envision that a cluster-scoped installation of CAM (what exists today) should not be impacted from the non-admin work. So when a user creates a `migplan`, they can simply use the privileged SA tokens as the `srcToken` and `destToken` fields in the identity secret. How can the UX be updated to associate identities with migclusters at plan creation time? How can migclusters be validated if they don't have an associated token at creation time? Let's chat through this further.

**Comment by eriknelson** [comment]
@vconzola FYI, before our meeting later this week @dymurray did a dump here from their conversations.

**Comment by dymurray** [comment]
Based on our conversation today, here is what I captured as the desired changes for the UI to function with the non-admin architecture:
* The cluster administrator is responsible for creating the `migcluster` resource + the privileged service account secret in a protected namespace (`openshift-migration`).
* The cluster administrator will grant `use` access on the `migcluster` resource for a given user Bob
* The discovery service will be responsible for returning the list of migclusters available to Bob by running SAR checks on every migcluster in the protected namespace and checking if Bob has `use` verb access

**Comment by eriknelson** [comment]
Closing in favor of #882
