### ISSUE TITLE
UI should redirect to OCP login page when oauth token expires

### ISSUE THREAD

**Issue by dymurray** [konveyor/mig-ui#798]
When an oauth token expires, the UI will show no data as if the CAM tool isn't configured at all. It takes refreshing the browser cache in order for the CAM tool to properly redirect to the login page and show the proper status of CAM.

It would be nice if this was detected and done automatically.

**Comment by eriknelson** [comment]
This is a regression unfortunately, I had gone through and systemically fixed this and it doesn't appear to be happening anymore. Need to look into what broke that.
