### ISSUE TITLE
Bug 1823920 - Default storageclass in dropdown defaults to None instead of controller recommendation

### ISSUE THREAD

**Issue by eriknelson** [konveyor/mig-ui#804]
Copied from: https://bugzilla.redhat.com/show_bug.cgi?id=1823920

Source cluster: mig-agnosticd 3.11 cluster
Targte cluster: mig-agnosticd 4.3.12 cluster (gp2 default storageclass)

As of master https://github.com/konveyor/mig-ui/commit/3ae13bb7c90b998019f118bc4769721cfae1e5aa

When selecting a namespace with a stateful workload and choosing copy for the pv action, the storageclass assignment screen currently defaults to displaying "None" instead of the controller specified default storageclass, as it did previously.

On the example clusters that I used, this results in a stage hanging during the restore process. The default value should have been gp2. This is a regression from previous behavior.

**Comment by mturley** [comment]
I have a fix in progress as part of my work for https://github.com/konveyor/mig-ui/issues/587. Assigning.
