### ISSUE TITLE
Wizard Plan Name validation error hint is not displayed

### ISSUE THREAD

**Issue by gildub** [konveyor/mig-ui#812]
When typing an invalid Plan name (for instance `abc--`) the validation error hint is not displayed.

**Comment by mturley** [comment]
This is one of the things I mentioned in https://github.com/konveyor/mig-ui/issues/774, but we could keep them separate (this one for the validation message, the other for preventing the user from proceeding with a name that is taken)

**Comment by gildub** [comment]
@mturley Sorry I missed issue #774. +1 re splitting the two issues.

**Comment by gildub** [comment]
@mturley, sorry for doubling up on this one, closing it. Thanks

**Comment by mturley** [comment]
No worries!
