### ISSUE TITLE
 Determine default SSL verify state and add hint text

### ISSUE THREAD

**Issue by eriknelson** [konveyor/mig-ui#829]
The current default behavior for adding a cluster has the SSL verify checkbox
checked. This is going to lead to a LOT of failed connections if people skip
the option because they don't know what it does, and they're using a self-signed
cert for their cluster.

We should think about what the default state for this checkbox should be for
both clusters and storage, update the code to reflect that, and add hint text
that steers the user in the right direction so they know when they should check
the box, and when they will need to upload their CA.

**Comment by eriknelson** [comment]
@jwmatthews Curious your opinion on what should be the default state for this box?

**Comment by eriknelson** [comment]
Related #779, #663, @mturley will be hitting these together.

**Comment by eriknelson** [comment]
Discussed this with @jwmatthews. We plan to address #779 by Splitting the S3 configuration into two different forms: AWS S3, and S3 (used for minio, noobaa, other custom S3 options).

Re: default checkbox state:
* Cluster should default to unchecked, AWS S3 should simply default to SSL verify, and the custom CA upload can be removed. We suspect the same for GCP and Azure, but let's leave the SSL options on those forms, but default to **checked**. For "S3", we should leave the checkbox unchecked, but the hint text will provide guidance for when it must be uploaded.

Will follow up with hint text.

**Comment by mturley** [comment]
For posterity: the hint text for these is here: https://github.com/konveyor/mig-ui/issues/663#issuecomment-619101758
and the GCP and Azure forms don't have SSL options currently, so I'm ignoring that part for now
