### ISSUE TITLE
UI doesn't show "Cancel" itinerary progress

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-ui#863]
I expected that mig-ui would show progression through "Cancel" itinerary stages similar to what shows up for the main "Stage" and "Final" itineraries. 

The step name is shown, but not the progress bar or percent completion.

Was this a conscious decision made to not include cancel progress, or is this a bug?

**Comment by ibolton336** [comment]
![image](https://user-images.githubusercontent.com/11218376/83069378-c6f7de80-a037-11ea-89e1-f0be3449d9a2.png)

@djwhatle  This may be fixed now. Wondering what you were seeing here. MAybe a specific case that has been fixed now?

**Comment by ibolton336** [comment]
Currently when a migration or stage is running, we set the step name/progress bar title to the running condition's "reason" value.
