### ISSUE TITLE
"Verify copy" tooltip text

### ISSUE THREAD

**Issue by apinnick** [konveyor/mig-ui#866]
I recommend rewording the tooltip for the "Verify copy" check box in the "Create a migration plan" UI, "Copy options" screen.

[Screenshot](https://user-images.githubusercontent.com/811963/79512150-d33b5580-800e-11ea-9f70-bd18ea7f111e.png)

The check box is only enabled for PVs with filesystem copy method, so there is no need to say when it is available.

Suggested text:

Each file is verified with a checksum, which significantly reduces performance.

**Comment by eriknelson** [comment]
@vconzola ack?

**Comment by vconzola** [comment]
@eriknelson I disagree with the first part. I think we need to explain why some of the checkboxes are disabled. Otherwise it will be confusing to users. I agree with changing the text of the second sentence.
