### ISSUE TITLE
Text of GVK incompatibility warning

### ISSUE THREAD

**Issue by apinnick** [konveyor/mig-ui#867]
The GVK incompatibility warning contains the following text: `Some namespaces contain GVKs incompatible with destination cluster`.

Change `destination` to `target` for consistency with the rest of UI.

**Comment by eriknelson** [comment]
@vconzola ack?

**Comment by vconzola** [comment]
@eriknelson Yes. Good catch.

**Comment by apinnick** [comment]
> @eriknelson Yes. Good catch.

@vconzola  My catch.

**Comment by ibolton336** [comment]
This is a message pulled from the controller condition. Would need to move this over to https://github.com/konveyor/mig-controller
