### ISSUE TITLE
Implement tokens screen

### ISSUE THREAD

**Issue by eriknelson** [konveyor/mig-ui#885]
Need to implement token management screen with a link in the left nav of the
application.

Table should have a type column indicating whether it is an OAuth or SA type
(this should be made available after the token has been created by the controller
annotating this information on the `MigToken` object inside `status`). It will
list the associated cluster, as well as the expiration (also set by the controller
in the status field).

The tokens each have a "Status" that indicates if its Expired, Expiring soon,
or ok.

Expiring soon threshold should be easy to change, though probably doesn't require a
configmap value. Maybe 2 hours to start with.

**Comment by mturley** [comment]
This was auto-closed by merging #899 because of my poor phrasing of "Remaining work to close #885 after this..." 😆 reopening since I imagine we only want to close this when it's working end-to-end with the API, right @eriknelson ?

**Comment by eriknelson** [comment]
+1,its kind of broad in scope maybe we can come back to this and add some sub tasks. It should be open. Funny I saw your PR and figured it wouldn't actually close this one but I guess we have our answer
