### ISSUE TITLE
Implement non-admin MigPlan General step

### ISSUE THREAD

**Issue by eriknelson** [konveyor/mig-ui#889]
WIP

This issue spans dedicating the general step for cluster name, and adding
cluster src, dest designation, in addition to adding the new token assignment.

It's likely this will spawn other issues as the mocks continue to evolve to
be more of a guided flow that allows the user to add things like tokens to their
migration if they haven't already added one.

**Comment by eriknelson** [comment]
![image](https://user-images.githubusercontent.com/410933/83455057-3d775080-a42b-11ea-906a-2004376134d9.png)

**Comment by mturley** [comment]
Latest mockups: https://docs.google.com/presentation/d/1JU_Lw1A-gUO4gBRofZzi74aONcknYRHbqBl_xHxikYQ/edit#slide=id.g8482032e20_0_44
