### ISSUE TITLE
Namespaces [cam-test] not found on the source cluster in CAM CLI

### ISSUE THREAD

**Issue by ashoks27** [konveyor/mig-ui#995]
Hello Team ,

I have read some comments saying the " Namespace not found on source Cluster " issue has been fixed in some thread, But I still I am getting this error in my CAM CLI in openshift version 4.4 . Could you please let to know how it can be fixed. Thansk.

**Comment by eriknelson** [comment]
>CAM CLI in openshift version 4.4 

Can you elaborate a bit? This is the UI repo, not sure if you mean the CLI as in the `MigPlan` CR or something else?

**Comment by ashoks27** [comment]
Hi Erik ,

I think I posted the question in wrong group. I am trying to migrate an application via CAM CLI and getting the " Namespace not found on source Cluster " error in Migplan. Please let me know the correct group to whom I can ask

**Comment by eriknelson** [comment]
@ashoks27 No problem! There isn't really a dedicated CLI project because really it's just a k8s API that our controller manages, so the best place for you to dig into this is probably the controller repo: https://github.com/konveyor/mig-controller
